var unasPalabras = [];
var cantidadPalabras = 0;
var palabra;
var elnumeroRandom;
var elnumeroRandomOtros;
var seleccionadoNativo = 0; //0 nativo ; 1 Nuevo
var cantidadRadioButton = 5;
	
$(function () {
	Load();
});	

function Load()
{
	SeteoVariablesGlobales();
	document.getElementById("rbtn1").checked = 1;
	PracticarUnoNuevo();
}	
function SeteoVariablesGlobales()
{
	//document.getElementById("lblResultado").style.visibility = "hidden";
	//$("#lblEstado").text("0/1");
palabra = { PalabraNativa:"cut down on", PalabraTraducida:"reducir la cantidad"};	
	unasPalabras[0] = palabra;
palabra = { PalabraNativa:"catch up with", PalabraTraducida:"alcanzar el mismo nivel"};	
	unasPalabras[1] = palabra;
palabra = { PalabraNativa:"come up against", PalabraTraducida:"enfrentar"};	
	unasPalabras[2] = palabra;
palabra = { PalabraNativa:"come up with", PalabraTraducida:"meditar"};	
	unasPalabras[3] = palabra;
palabra = { PalabraNativa:"drop in on", PalabraTraducida:"cayeron"};	
	unasPalabras[4] = palabra;
palabra = { PalabraNativa:"face up", PalabraTraducida:"enfrentar"};	
	unasPalabras[5] = palabra;
palabra = { PalabraNativa:"feel up to", PalabraTraducida:"comodo"};	
	unasPalabras[6] = palabra;
palabra = { PalabraNativa:"get away with", PalabraTraducida:"evitar ser descubierto"};	
	unasPalabras[7] = palabra;
palabra = { PalabraNativa:"get along with", PalabraTraducida:"llevarse bien"};	
	unasPalabras[8] = palabra;
palabra = { PalabraNativa:"get on with", PalabraTraducida:"continuar"};	
	unasPalabras[9] = palabra;
palabra = { PalabraNativa:"get out of", PalabraTraducida:"evitar llegar tarde"};	
	unasPalabras[10] = palabra;
palabra = { PalabraNativa:"get round to", PalabraTraducida:"hacerse tiempo"};	
	unasPalabras[11] = palabra;
palabra = { PalabraNativa:"get up to", PalabraTraducida:"hacer algo malo"};	
	unasPalabras[12] = palabra;
palabra = { PalabraNativa:"go in for", PalabraTraducida:"tener un hobby"};	
	unasPalabras[13] = palabra;
palabra = { PalabraNativa:"grow out of", PalabraTraducida:"estar grande"};	
	unasPalabras[14] = palabra;
palabra = { PalabraNativa:"keep up with", PalabraTraducida:"permanecer en el mismo nivel"};	
	unasPalabras[15] = palabra;
palabra = { PalabraNativa:"look down on", PalabraTraducida:"sentirse superior"};	
	unasPalabras[16] = palabra;
palabra = { PalabraNativa:"look up to", PalabraTraducida:"respetar"};	
	unasPalabras[17] = palabra;
palabra = { PalabraNativa:"look forward to", PalabraTraducida:"esperar con ansiedad"};	
	unasPalabras[18] = palabra;
palabra = { PalabraNativa:"make up for", PalabraTraducida:"compensó"};	
	unasPalabras[19] = palabra;
palabra = { PalabraNativa:"put up with", PalabraTraducida:"tolerar"};	
	unasPalabras[20] = palabra;
palabra = { PalabraNativa:"run out of", PalabraTraducida:"quedarse sin"};	
	unasPalabras[21] = palabra;
palabra = { PalabraNativa:"stand up for", PalabraTraducida:"defenderse"};	
	unasPalabras[22] = palabra;
palabra = { PalabraNativa:"bring up", PalabraTraducida:"educar y criar"};	
	unasPalabras[23] = palabra;
palabra = { PalabraNativa:"carry out", PalabraTraducida:"llevar a cabo"};	
	unasPalabras[24] = palabra;
palabra = { PalabraNativa:"call off", PalabraTraducida:"cancelar"};	
	unasPalabras[25] = palabra;
palabra = { PalabraNativa:"clear up", PalabraTraducida:"limpiar"};	
	unasPalabras[26] = palabra;
palabra = { PalabraNativa:"clear up", PalabraTraducida:"mejorar"};	
	unasPalabras[27] = palabra;
palabra = { PalabraNativa:"fill in", PalabraTraducida:"completar formulario"};	
	unasPalabras[28] = palabra;
palabra = { PalabraNativa:"fill in", PalabraTraducida:"ocupar un puesto"};	
	unasPalabras[29] = palabra;
palabra = { PalabraNativa:"find out", PalabraTraducida:"descubrir"};	
	unasPalabras[30] = palabra;
palabra = { PalabraNativa:"give away", PalabraTraducida:"donar"};	
	unasPalabras[31] = palabra;
palabra = { PalabraNativa:"give away", PalabraTraducida:"dar a conocer"};	
	unasPalabras[32] = palabra;
palabra = { PalabraNativa:"give up", PalabraTraducida:"dejar un habito"};	
	unasPalabras[33] = palabra;
palabra = { PalabraNativa:"give up", PalabraTraducida:"intentar parar"};	
	unasPalabras[34] = palabra;
palabra = { PalabraNativa:"hold up", PalabraTraducida:"asaltar"};	
	unasPalabras[35] = palabra;
palabra = { PalabraNativa:"knock out", PalabraTraducida:"dejar inconsciente"};	
	unasPalabras[36] = palabra;
palabra = { PalabraNativa:"leave out", PalabraTraducida:"no incluir"};	
	unasPalabras[37] = palabra;
palabra = { PalabraNativa:"look up", PalabraTraducida:"ubicar un dato"};	
	unasPalabras[38] = palabra;
palabra = { PalabraNativa:"look up", PalabraTraducida:"parecer mejor"};	
	unasPalabras[39] = palabra;
palabra = { PalabraNativa:"make up", PalabraTraducida:"inventar historia"};	
	unasPalabras[40] = palabra;
palabra = { PalabraNativa:"make up", PalabraTraducida:"tomar una decisión"};	
	unasPalabras[41] = palabra;
palabra = { PalabraNativa:"pick up", PalabraTraducida:"pasar a buscar"};	
	unasPalabras[42] = palabra;
palabra = { PalabraNativa:"put aside", PalabraTraducida:"ahorrar"};	
	unasPalabras[43] = palabra;
palabra = { PalabraNativa:"put off", PalabraTraducida:"postergar"};	
	unasPalabras[44] = palabra;
palabra = { PalabraNativa:"put off", PalabraTraducida:"arruinar"};	
	unasPalabras[45] = palabra;
palabra = { PalabraNativa:"put up", PalabraTraducida:"dar alojamiento"};	
	unasPalabras[46] = palabra;
palabra = { PalabraNativa:"show around", PalabraTraducida:"mostrar"};	
	unasPalabras[47] = palabra;
palabra = { PalabraNativa:"take over", PalabraTraducida:"reemplazar el puesto de alguien"};	
	unasPalabras[48] = palabra;
palabra = { PalabraNativa:"tear up", PalabraTraducida:"cortar en pedacitos"};	
	unasPalabras[49] = palabra;
palabra = { PalabraNativa:"think over", PalabraTraducida:"meditar"};	
	unasPalabras[50] = palabra;
palabra = { PalabraNativa:"try out", PalabraTraducida:"estrenar"};	
	unasPalabras[51] = palabra;
palabra = { PalabraNativa:"turn down", PalabraTraducida:"rechazar"};	
	unasPalabras[52] = palabra;
palabra = { PalabraNativa:"wear out", PalabraTraducida:"cansar"};	
	unasPalabras[53] = palabra;
palabra = { PalabraNativa:"work out", PalabraTraducida:"encontrar una solucion"};	
	unasPalabras[54] = palabra;
			
	cantidadPalabras = unasPalabras.length;
}

